### ISSUE TITLE
Can't setup offline vagrant VM because of missing "dragncards_dev" database

### ISSUE THREAD

**Issue by guillaumehuet** [seastan/DragnCards#33]
Hello,

I tried to setup DragnCards for offline use to play in the train with the provided vagrant VM but I've been having errors and I can't troubleshoot the last one, could anyone please help me fix it?

So far the errors I found and corrected (might need code change) :
- `vagrant up` errored with
```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```
=> I've tried increasing the timeout but got the same error, the solution I found online was to open VirtualBox and show the VM after it's been started, I don't really understand why but this fixed the error. Could the setup of the VM be changed to avoid showing the VM when started?

- `cd: /home/vagrant/sql: No such file or directory dragncards` :
=> I changed line 92 of `vagrant/Vagrantfile` from `cd /home/vagrant/sql` to `cd /home/vagrant/files/sql`

The error I'm now facing is the following : `psql: error: FATAL:  database "dragncards_dev" does not exist`.
This seems to come from `sudo su postgres -c "psql -d dragncards_dev -f /home/vagrant/files/sql/users.sql"`.
I searched for `dragncards_dev` in the code to find where the database would be created and only found it in `backend\config\dev.exs`. This seems to be an Elixir file and I don't know anything about the way it is used but there is mentions of `Mix` and in the VM output I found :
```
    dragn: Could not install Hex because Mix could not download metadata at https://repo.hex.pm/installs/hex-1.x.csv.
    dragn:
    dragn: Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] Could not find Hex, which is needed to build dependency :phoenix
    dragn: ** (Mix) Could not find an SCM for dependency :phoenix from DragnCards.MixProject
```

My host OS is Windows 10, I've attached the PowerShell output when calling `vagrant up`, I found other warnings/errors that may or may not be relevant, I won't paste them all here but the lines are :
[Windows PowerShell.txt](https://github.com/seastan/DragnCards/files/10546789/Windows.PowerShell.txt)
- 37-42 (NB, I tried with and without `vagrant-vbguest` but the result is the same and I tried to SSH into the VM and can access the shared folder without any problem even without the plugin so I don't think this is relevant)
- 471-510
- 560-614
- 664-668

Thank you for your awesome plateform, hoping I will be able to play offline soon!

Guillaume
